language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "MlDlM5laokXi1v5lVVpySXRyw6MMCtJmieR14HUNOR+NC/BalLc8q/PDzAoJBlW11k0pUpe4x8mTVgWFrP+aj8UWCWbO+cl8W2J4cb/Eaxnio5nxyXRzlYmFtE1xO+8JJmNQZ+TXbW/s5pYI/h4OGU4PDz5LNsReVdRoTNoLeIiKaS4aLQJFghGVPxay9ZdxA+RAE0A+Q+pvqZJISeo90im9Wjvw85Ehavu9mloBizN/T7EcIPVMwCuR0iMRpNewo3R+6LIg3Ye4bmHfsCdC0Nxrc6TIEhvk4LYAl6TiWegf/23DkGdJQ8r/d0CIYjaiqzQRPKQZRYSdDvbAqmDPjc9yNf0NNPhmvfKx8DN7BHz5HZGb1mgsb/zujVPjCewMnYhwOmL4BotBsAr4AE1WziDQbr3FR0rGuHCRLhiPI005C0hMAGaIevjSjEwRKRcDt4QLrnYdj1BDa1OqIIMZwKBMf6hqDEe+akozmfPUdx4358AXxA8JeuMpK5lQak3xP/LVovjDWRjoG+fFCVh7fXVgA+apQvDSBRaVaH69xs8eKrH5Bb6eJGd9GeVo6G8cGsCK1BgSHTJcfIu+ef4EpvWgFZZS5SiMTNdqZURGDUSwS7wwe33rlsuNvCfHALmTlPvPjPtlPuaJDRN7zp9Fh5TZeZB7sTciGbRKTenLbfY="
